const ADD_CLAUDRON_ARM = 'app/factory/redux/ADD_CLAUDRON_ARM';
const ADD_CLAUDRON_LEG = 'app/factory/redux/ADD_CLAUDRON_LEG';
const ADD_CLAUDRON_CUCUMBER = 'app/factory/redux/ADD_CLAUDRON_CUCUMBER';
const ODD_CLAUDRON_ARM = 'app/factory/redux/ODD_CLAUDRON_ARM';
const ODD_CLAUDRON_LEG = 'app/factory/redux/ODD_CLAUDRON_LEG';
const ODD_CLAUDRON_CUCUMBER = 'app/factory/redux/ODD_CLAUDRON_CUCUMBER';

export default {
  ADD_CLAUDRON_ARM,
  ADD_CLAUDRON_LEG,
  ADD_CLAUDRON_CUCUMBER,
  ODD_CLAUDRON_ARM,
  ODD_CLAUDRON_LEG,
  ODD_CLAUDRON_CUCUMBER
};
